import type { PostureInput } from "@/assessment/types";
import * as rulaScorers from "@/assessment/rula/rula";
import * as rebaScorers from "@/assessment/reba/reba";

/**
 * Single source of truth for "measured angle vs banding" rows shown in the UI
 * and the PDF's per-joint table. Rows are GENERATED by calling the exact same
 * exported scorer functions the assessment uses, so the displayed bands can
 * never drift from the scoring itself.
 */

export interface JointThresholdRow {
  joint: string;
  /** Measured value, degrees (undefined → not measured). */
  measuredDeg?: number;
  /** Human-readable band the measured value falls in, e.g. "20–45°". */
  band: string;
  /** The component score this band maps to (before modifier flags). */
  score: number;
  /** The next band boundary that would raise the score, if any. */
  nextThreshold?: string;
}

interface BandDef {
  /** Inclusive lower edge of the band (degrees). */
  from: number;
  /** Exclusive upper edge (degrees); Infinity for the last band. */
  to: number;
  label: string;
}

/** Derive contiguous bands for a scorer by sampling it across a degree range.
 * Sampling the real function (1° steps) guarantees fidelity to the code. */
function deriveBands(score: (deg: number) => number, from: number, to: number): { band: BandDef; score: number }[] {
  const out: { band: BandDef; score: number }[] = [];
  let start = from;
  let current = score(from);
  for (let d = from + 1; d <= to; d++) {
    const s = score(d);
    if (s !== current) {
      out.push({ band: { from: start, to: d, label: `${start}° to ${d - 1}°` }, score: current });
      start = d;
      current = s;
    }
  }
  out.push({ band: { from: start, to: Infinity, label: `${start}°+` }, score: current });
  return out;
}

function rowFor(
  joint: string,
  measured: number | undefined,
  bands: { band: BandDef; score: number }[],
): JointThresholdRow {
  if (measured === undefined) {
    return { joint, band: "not measured", score: 0 };
  }
  const clamped = Math.round(measured);
  const idx = bands.findIndex((b) => clamped >= b.band.from && clamped < b.band.to);
  const hit = bands[idx] ?? bands[bands.length - 1];
  // The next band that yields a HIGHER score, scanning upward.
  const next = bands.slice(idx + 1).find((b) => b.score > hit.score);
  return {
    joint,
    measuredDeg: measured,
    band: hit.band.label,
    score: hit.score,
    nextThreshold: next ? `score ${next.score} at ${next.band.from}°` : undefined,
  };
}

/** Per-joint threshold rows for a method, from the live input. */
export function thresholdRows(methodId: string, input: PostureInput): JointThresholdRow[] {
  if (methodId === "reba") {
    return [
      rowFor("Upper arm", input.upperArmAngle, deriveBands((d) => rebaScorers.upperArmScore(d, false, false, false), -45, 170)),
      rowFor("Lower arm", input.lowerArmAngle, deriveBands((d) => rebaScorers.lowerArmScore(d), 0, 170)),
      rowFor("Wrist", input.wristAngle, deriveBands((d) => rebaScorers.wristScore(d, false), -60, 60)),
      rowFor("Neck", input.neckAngle, deriveBands((d) => rebaScorers.neckScore(d, false, false), -45, 80)),
      rowFor("Trunk", input.trunkAngle, deriveBands((d) => rebaScorers.trunkScore(d, false, false), 0, 110)),
      rowFor("Knee", input.legAngle, deriveBands((d) => rebaScorers.legsScore(true, d, false), 0, 150)),
    ];
  }
  // OWAS uses category codes rather than graded angle bands; RULA is default.
  return [
    rowFor("Upper arm", input.upperArmAngle, deriveBands((d) => rulaScorers.upperArmScore(d, false, false, false), -45, 170)),
    rowFor("Lower arm", input.lowerArmAngle, deriveBands((d) => rulaScorers.lowerArmScore(d, false), 0, 170)),
    rowFor("Wrist", input.wristAngle, deriveBands((d) => rulaScorers.wristScore(d, false), -60, 60)),
    rowFor("Neck", input.neckAngle, deriveBands((d) => rulaScorers.neckScore(d, false, false), -45, 80)),
    rowFor("Trunk", input.trunkAngle, deriveBands((d) => rulaScorers.trunkScore(d, false, false), 0, 110)),
  ];
}
